# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanArchitechtureTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxDataSources'
  pod 'Action'
  pod 'Alamofire', '~> 4.9.1'
  pod 'ObjectMapper'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Quick'
  pod 'Nimble'

  # Pods for CleanArchitechtureTutorial

  target 'CleanArchitechtureTutorialTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxDataSources'
    pod 'ObjectMapper'
    pod 'Quick'
    pod 'Nimble'
    
  end

  target 'CleanArchitechtureTutorialUITests' do
    # Pods for testing
  end

end
